### ISSUE TITLE
Ubuntu 20.04 current issues

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#598]
- [x] spatial, images, doi: postgresql/postgis package missing
- [x] cas:  `Unknown system variable 'tx_isolation'`  with `5.3.12-2` and `6.5.6-1` (https://github.com/AtlasOfLivingAustralia/ala-cas-5/issues/50)
- [x] `ERROR 1267 (HY000) at line 2 in file: '/data/userdetails/setup/auth-ip.sql': Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT)` in `userdetails`.
- [x] spatial: `The target XML source '/data/geoserver_data_dir/gwc-gs.xml' does not exist.`
- [x] Mysql 8 login issues #604 
- [ ] postgresql not available for ubuntu focal (#920)

**Comment by vjrj** [comment]
The last one is caused by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956804 so `GEOSERVER_DATA_DIR` is not setted correctly.

**Comment by vjrj** [comment]
Unchecking pg part, as #600 was reverted
